services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSGRES_DB: taskping
    ports:
      - "5432: 54320"
    volumes:
      - ./data:/var/lib/posgresql/data